plugin:
    name: 'API Content Manager'
    description: 'Generate clean API JSON output with OctoberCMS to your JS front-ends (ReactJS, ReactNative, Angular...)'
    author: 'Acte Solutions'
    icon: oc-icon-file-code-o
    homepage: 'https://github.com/acte-solutions/oc-plugin-contentmanager'
permissions:
    acte.contentmanager.manage_fields:
        tab: 'acte.contentmanager::lang.plugin.name'
        label: 'Manage fields'
    acte.contentmanager.manage_fieldtypes:
        tab: 'acte.contentmanager::lang.plugin.name'
        label: 'Manage field types'
    acte.contentmanager.manage_formats:
        tab: 'acte.contentmanager::lang.plugin.name'
        label: 'Manage image formats'
navigation:
    contentmanager:
        label: 'Content Manager'
        url: acte/contentmanager/elements
        icon: icon-file-code-o
        permissions:
            - acte.contentmanager.manage_fields
        sideMenu:
            elements:
                label: Elements
                url: acte/contentmanager/elements
                icon: icon-sitemap
                permissions:
                    - acte.contentmanager.manage_fields
            fields:
                label: Fields
                url: acte/contentmanager/fields
                icon: icon-cubes
                permissions:
                    - acte.contentmanager.manage_fields
            fieldtypes:
                label: 'Field Types'
                url: acte/contentmanager/fieldtypes
                icon: icon-list-alt
                permissions:
                    - acte.contentmanager.manage_fieldtypes
            formats:
                label: 'Image formats'
                url: acte/contentmanager/formats
                icon: icon-image
                permissions:
                    - acte.contentmanager.manage_formats
                attributes: {  }
