list: $/acte/contentmanager/models/format/columns.yaml
modelClass: Acte\ContentManager\Models\Format
title: Formats
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'acte/contentmanager/formats/update/:id'
