list: $/acte/contentmanager/models/element/columns.yaml
modelClass: Acte\ContentManager\Models\Element
title: Elements
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'acte/contentmanager/elements/update/:id'
