list: $/acte/contentmanager/models/fieldtype/columns.yaml
modelClass: Acte\ContentManager\Models\FieldType
title: FieldTypes
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'acte/contentmanager/fieldtypes/update/:id'
